# This is a basic workflow to help you get started with Actions

name: CI-19122020

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testig:
    runs-on: ubuntu-latest
    steps:
      - name: my-testing-step-1
        run: echo world
    
  my-build:
    runs-on: ubuntu-latest
    steps:
      - name: my-build-step-1
        run: echo world
    
